### ISSUE TITLE
README needs something visual

### ISSUE THREAD

**Issue by annakrystalli** [annakrystalli/rmacroRDM#1]
Hi!

I'd really like some sort of visual representation in the README of either the problem described or the solution that the package is proposed to address.

Can anyone out there help?

@demitri?

**Comment by demitri** [comment]
Sorry I didn't reply! I don't have any specific answer - it's not an easy thing and I'm definitely not a good artist!

**Comment by annakrystalli** [comment]
Haha no worries. Just been preparing the repo for the global sprint. You should check it out! Any feedback welcome !

Also are you sprinting this year?
